
package com.mycompany.aplikasiperpus;

import java.awt.Color;

/**
 *
 * @author royka
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());

    /**
     * Creates new form DashboardPerpus
     */
    
    Color DefaultColor,ClickedColor;
    public DashboardAdmin() {
        initComponents();
        DefaultColor = new Color(255,255,255);
        ClickedColor= new Color(0,153,153);
        
        Dashboard.setBackground(DefaultColor);
        Book.setBackground(DefaultColor);
        DaftarAnggota.setBackground(DefaultColor);
        Peminjaman.setBackground(DefaultColor);
        Pengembalian.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MenuName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        DaftarAnggota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Book = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Peminjaman = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Pengembalian = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuName.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        MenuName.setForeground(new java.awt.Color(255, 255, 255));
        MenuName.setText("Haii!!! Selamat Datang Admin");
        jPanel2.add(MenuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Perpustakaan Digital");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1120, 130));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DaftarAnggota.setBackground(new java.awt.Color(255, 255, 255));
        DaftarAnggota.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DaftarAnggotaMouseMoved(evt);
            }
        });
        DaftarAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DaftarAnggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DaftarAnggotaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DaftarAnggotaMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("DAFTAR ANGGOTA");

        javax.swing.GroupLayout DaftarAnggotaLayout = new javax.swing.GroupLayout(DaftarAnggota);
        DaftarAnggota.setLayout(DaftarAnggotaLayout);
        DaftarAnggotaLayout.setHorizontalGroup(
            DaftarAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarAnggotaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        DaftarAnggotaLayout.setVerticalGroup(
            DaftarAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.add(DaftarAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 60));

        Book.setBackground(new java.awt.Color(255, 255, 255));
        Book.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BookMouseMoved(evt);
            }
        });
        Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BookMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("BOOK");

        javax.swing.GroupLayout BookLayout = new javax.swing.GroupLayout(Book);
        Book.setLayout(BookLayout);
        BookLayout.setHorizontalGroup(
            BookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel3)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        BookLayout.setVerticalGroup(
            BookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.add(Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, 60));

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DashboardMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DashboardMouseMoved(evt);
            }
        });
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DashboardMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("DASHBOARD");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel4)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 60));

        Peminjaman.setBackground(new java.awt.Color(255, 255, 255));
        Peminjaman.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PeminjamanMouseMoved(evt);
            }
        });
        Peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeminjamanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PeminjamanMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("PEMINJAMAN");

        javax.swing.GroupLayout PeminjamanLayout = new javax.swing.GroupLayout(Peminjaman);
        Peminjaman.setLayout(PeminjamanLayout);
        PeminjamanLayout.setHorizontalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeminjamanLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        PeminjamanLayout.setVerticalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeminjamanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.add(Peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, 60));

        Pengembalian.setBackground(new java.awt.Color(255, 255, 255));
        Pengembalian.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PengembalianMouseMoved(evt);
            }
        });
        Pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PengembalianMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PengembalianMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("PENGEMBALIAN");

        javax.swing.GroupLayout PengembalianLayout = new javax.swing.GroupLayout(Pengembalian);
        Pengembalian.setLayout(PengembalianLayout);
        PengembalianLayout.setHorizontalGroup(
            PengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengembalianLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        PengembalianLayout.setVerticalGroup(
            PengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PengembalianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.add(Pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 260, 60));

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoutMouseMoved(evt);
            }
        });
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("LOGOUT");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(96, 96, 96))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 260, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 137, 310, 740));

        jDesktopPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 810, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMousePressed
        // TODO add your handling code here:
        MenuName.setText("Dashboard Admin");
    }//GEN-LAST:event_DashboardMousePressed

    private void BookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookMousePressed
        // TODO add your handling code here
        MenuName.setText("Book");
    }//GEN-LAST:event_BookMousePressed

    private void DaftarAnggotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarAnggotaMousePressed
        // TODO add your handling code here:
        MenuName.setText("Daftar Anggota");
    }//GEN-LAST:event_DaftarAnggotaMousePressed

    private void PeminjamanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanMousePressed
        // TODO add your handling code here:
        MenuName.setText("Peminjaman");
    }//GEN-LAST:event_PeminjamanMousePressed

    private void PengembalianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianMousePressed
        // TODO add your handling code here:
        MenuName.setText("Pengembalian");
    }//GEN-LAST:event_PengembalianMousePressed

    private void LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMousePressed
        // TODO add your handling code here:
        FormLogin formLogin = new FormLogin();
        this.dispose();
        formLogin.setVisible(true);
    }//GEN-LAST:event_LogoutMousePressed

    private void DaftarAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarAnggotaMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DaftarAnggotaMouseEntered

    private void DashboardMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DashboardMouseDragged

    private void DashboardMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseMoved
        // TODO add your handling code here:
        Dashboard.setBackground(ClickedColor);
        Book.setBackground(DefaultColor);
        DaftarAnggota.setBackground(DefaultColor);
        Peminjaman.setBackground(DefaultColor);
        Pengembalian.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
   
        
    }//GEN-LAST:event_DashboardMouseMoved

    private void BookMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookMouseMoved
        // TODO add your handling code here:
        Dashboard.setBackground(DefaultColor);
        Book.setBackground(ClickedColor);
        DaftarAnggota.setBackground(DefaultColor);
        Peminjaman.setBackground(DefaultColor);
        Pengembalian.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_BookMouseMoved

    private void DaftarAnggotaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarAnggotaMouseMoved
        // TODO add your handling code here:
        Dashboard.setBackground(DefaultColor);
        Book.setBackground(DefaultColor);
        DaftarAnggota.setBackground(ClickedColor);
        Peminjaman.setBackground(DefaultColor);
        Pengembalian.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_DaftarAnggotaMouseMoved

    private void PeminjamanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanMouseMoved
        // TODO add your handling code here:
        Dashboard.setBackground(DefaultColor);
        Book.setBackground(DefaultColor);
        DaftarAnggota.setBackground(DefaultColor);
        Peminjaman.setBackground(ClickedColor);
        Pengembalian.setBackground(DefaultColor);
        Logout.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_PeminjamanMouseMoved

    private void PengembalianMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianMouseMoved
        // TODO add your handling code here:
        Dashboard.setBackground(DefaultColor);
        Book.setBackground(DefaultColor);
        DaftarAnggota.setBackground(DefaultColor);
        Peminjaman.setBackground(DefaultColor);
        Pengembalian.setBackground(ClickedColor);
        Logout.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_PengembalianMouseMoved

    private void LogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseMoved
        // TODO add your handling code here:
        Dashboard.setBackground(DefaultColor);
        Book.setBackground(DefaultColor);
        DaftarAnggota.setBackground(DefaultColor);
        Peminjaman.setBackground(DefaultColor);
        Pengembalian.setBackground(DefaultColor);
        Logout.setBackground(ClickedColor);
        
        
    }//GEN-LAST:event_LogoutMouseMoved

    private void BookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookMouseClicked
        // TODO add your handling code here:
        Book book = new Book();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(book).setVisible(true);
    }//GEN-LAST:event_BookMouseClicked

    private void DaftarAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarAnggotaMouseClicked
        // TODO add your handling code here:
        DaftarAnggota daftar = new DaftarAnggota();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(daftar).setVisible(true);
    }//GEN-LAST:event_DaftarAnggotaMouseClicked

    private void PeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanMouseClicked
        // TODO add your handling code here:
        Peminjaman minjam = new Peminjaman();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(minjam).setVisible(true);
    }//GEN-LAST:event_PeminjamanMouseClicked

    private void PengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianMouseClicked
        // TODO add your handling code here:
        Pengembalian kembali = new Pengembalian();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(kembali).setVisible(true);
    }//GEN-LAST:event_PengembalianMouseClicked

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Book;
    private javax.swing.JPanel DaftarAnggota;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel MenuName;
    private javax.swing.JPanel Peminjaman;
    private javax.swing.JPanel Pengembalian;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
