package com.mycompany.aplikasiperpus;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Book extends javax.swing.JInternalFrame {

    /**
     * Creates new form Book
     */
    public Book() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelBook = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(810, 580));

        PanelBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(PanelBook);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("List Buku");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(315, 315, 315)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 94, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDataBook() {
    // model dengan nama kolom; kita override isCellEditable agar kolom No & ID tidak bisa diedit
    DefaultTableModel model = new DefaultTableModel(
        new Object[] {"No", "ID", "Judul", "Penulis", "Tahun", "Stok"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // kolom 0 (No) dan 1 (ID) tidak boleh diedit oleh user
            return column != 0 && column != 1;
        }
    };

    try (Connection c = Koneksi.getConnection();
         Statement s = c.createStatement();
         ResultSet r = s.executeQuery("SELECT * FROM buku")) {

        int no = 1;
        while (r.next()) {
            model.addRow(new Object[] {
                no++,                       // No (urutan tampilan)
                r.getInt("id_buku"),        // ID (dipakai internal, nanti disembunyikan)
                r.getString("judul"),
                r.getString("penulis"),
                r.getInt("tahun"),
                r.getInt("stok")
            });
        }

        PanelBook.setModel(model);

        // Sembunyikan kolom ID secara visual (tetap ada di model)
        // Pastikan ada setAutoCreateRowSorter(false) dulu kalau mau konsisten
        if (PanelBook.getColumnModel().getColumnCount() > 1) {
            PanelBook.getColumnModel().getColumn(1).setMinWidth(0);
            PanelBook.getColumnModel().getColumn(1).setMaxWidth(0);
            PanelBook.getColumnModel().getColumn(1).setPreferredWidth(0);
        }

        // (opsional) set lebar kolom No kecil
        PanelBook.getColumnModel().getColumn(0).setPreferredWidth(40);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
}
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String judul = JOptionPane.showInputDialog("Judul Buku:");
        String penulis = JOptionPane.showInputDialog("Penulis:");
        String tahun = JOptionPane.showInputDialog("Tahun:");
        String stok = JOptionPane.showInputDialog("Stok:");

        try {
            Connection c = Koneksi.getConnection();

            // ambil id terakhir
            String sqlGetId = "SELECT IFNULL(MAX(id_buku), 0) + 1 AS nextId FROM buku";
            PreparedStatement psId = c.prepareStatement(sqlGetId);
            ResultSet rs = psId.executeQuery();
            int nextId = 1;
            if (rs.next()) {
                nextId = rs.getInt("nextId");
            }

            // insert data
            String sql = "INSERT INTO buku (id_buku, judul, penulis, tahun, stok) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setInt(1, nextId);
            p.setString(2, judul);
            p.setString(3, penulis);
            p.setInt(4, Integer.parseInt(tahun));
            p.setInt(5, Integer.parseInt(stok));
            p.executeUpdate();

            JOptionPane.showMessageDialog(this, "Buku berhasil ditambahkan");
            loadDataBook(); // refresh tabel
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tambah buku: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int viewRow = PanelBook.getSelectedRow();
        if (viewRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Convert view row ke model row (aman kalau ada sorter)
        int modelRow = PanelBook.convertRowIndexToModel(viewRow);
        javax.swing.table.TableModel model = PanelBook.getModel();

        // Ambil dari model dengan index kolom yang sesuai:
        // 0 = No, 1 = ID, 2 = Judul, 3 = Penulis, 4 = Tahun, 5 = Stok
        String id = model.getValueAt(modelRow, 1).toString();
        String judul = model.getValueAt(modelRow, 2).toString();
        String penulis = model.getValueAt(modelRow, 3).toString();
        String tahun = model.getValueAt(modelRow, 4).toString();
        String stok = model.getValueAt(modelRow, 5).toString();

        // Tampilkan dialog edit (default value dari data saat ini)
        String newJudul   = JOptionPane.showInputDialog(this, "Edit Judul:", judul);
        String newPenulis = JOptionPane.showInputDialog(this, "Edit Penulis:", penulis);
        String newTahun   = JOptionPane.showInputDialog(this, "Edit Tahun:", tahun);
        String newStok    = JOptionPane.showInputDialog(this, "Edit Stok:", stok);

        // kalau cancel di salah satu dialog, batalkan update
        if (newJudul == null || newPenulis == null || newTahun == null || newStok == null) {
            return;
        }

        try (Connection c = Koneksi.getConnection();
             PreparedStatement p = c.prepareStatement(
                 "UPDATE buku SET judul=?, penulis=?, tahun=?, stok=? WHERE id_buku=?")) {

            p.setString(1, newJudul);
            p.setString(2, newPenulis);
            p.setInt(3, Integer.parseInt(newTahun));
            p.setInt(4, Integer.parseInt(newStok));
            p.setInt(5, Integer.parseInt(id));

            p.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            loadDataBook(); // refresh tabel
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int viewRow = PanelBook.getSelectedRow();
        if (viewRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int modelRow = PanelBook.convertRowIndexToModel(viewRow);
        javax.swing.table.TableModel model = PanelBook.getModel();
        String id = model.getValueAt(modelRow, 1).toString(); // kolom 1 = ID

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try (Connection c = Koneksi.getConnection();
                 PreparedStatement p = c.prepareStatement("DELETE FROM buku WHERE id_buku=?")) {

                p.setInt(1, Integer.parseInt(id));
                p.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                loadDataBook();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadDataBook(); // panggil ulang fungsi untuk load data buku
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PanelBook;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
